title: <p align="center"> Ankush Kshirsagar </p>
logo: /assets/img/logo.png
description: 
  <p align="center">
  <a href="https://github.com/AnkushKshirsagar">GitHub</a><br>
  I have 11 years of experiecne, during which I got a chance to explore various technologies.
  </p>
show_downloads: false
theme: jekyll-theme-minimal
