title: <p align="center"> Ankush Kshirsagar </p>
logo: /assets/img/logo.png
description: I have 11 years of experiecne, during which I got a chance to explore various technologies.

theme: jekyll-theme-minimal
